### ISSUE TITLE
Stream-loader should load any record and redoer should produce json to queues

### ISSUE THREAD

**Issue by jeffadair** [Senzing/community-roadmap#39]
This may sound like two problems, but they are interrelated.

stream-loader only loads new records. It should be a bit more general and be able to load reeval/redo records and delete records too. It can do this by looking at DSRC_ACTION and calling the proper Senzing function accordingly:

> if it is D, deleteRecord
> if it is X, reevaluateRecord
> if it is A/C/null, addRecord

The redoer part of this is as such: Currently, the redo records are xml. redoer should convert a record to json, add a DSRC_ACTION of X, and then add it to the queue. This would allow redo records to be added to the general loading queue and make loading and redo all part of the same operation. We wouldn't have the loading queue empty but a separate redo queue still being processed.

**Comment by docktermj** [comment]
When considering this, we need to remember that there are queuing products like Kafka, Kinesis, etc. that have more than one consumer.   So if a redoer places a record on a queue, it may be also read by another non-Senzing process.  We can't just pollute queues with Senzing-internal data.  Queues, topics, etc. need to be single-purpose.

Whatever is done needs to be uniform across all queue product so that queuing components can be interchanged without semantic differences.

**Comment by docktermj** [comment]
Having said that, there are other approaches:

For instance, if the `stream-loader.py`  understood that there was the "normal" queue/topic and an optional second queue that might be considered for a different type of records, it (the stream-loader.py) could intersperse handling "normal" and "special" records.   This would keep the queues/topics single-purpose and still allow the ability to process redo records in a scalable manner.

**Comment by docktermj** [comment]
Another approach is to start two, independently scalable groups of stream-loaders.   The first group handles the "customer" queue.  the second queue handles senzing-internal records.  Again, this keeps the queues as "single-purpose".
